version: '2'
services:
  funnyvideos:
    image: funnyvideos
    build:
      context: .
    container_name: 'funnyvideos'
    # command: rails s -b 0.0.0.0 -p 3000
    command: sh -lc "tail -f log/development.log"
    # command: sh -lc "watch top"
    tty: true
    privileged: true
    environment:
      TERM: xterm-256color
      # POSTGRES_HOST: 'feeddb'
    volumes:
      - "./:/funnyvideos"
    ports:
      - 0.0.0.0:3000:3000
